# Generated by Django 4.2.4 on 2023-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="village", name="area",),
        migrations.AlterField(
            model_name="village",
            name="population",
            field=models.IntegerField(default=0),
        ),
    ]
