# Generated by Django 4.2.4 on 2023-09-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0002_remove_village_area_alter_village_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="addiction_recovery_camp_available",
            field=models.BooleanField(default=False, verbose_name="کمپ ترک اعتیاد"),
        ),
        migrations.AddField(
            model_name="village",
            name="artistic_figures",
            field=models.TextField(default="", verbose_name="شخصیت\u200cهای هنری"),
        ),
        migrations.AddField(
            model_name="village",
            name="asphalt_available",
            field=models.BooleanField(
                default=False, verbose_name="آسفالت، مسیر و معابر"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="bakery_available",
            field=models.BooleanField(default=False, verbose_name="نانوایی"),
        ),
        migrations.AddField(
            model_name="village",
            name="bank_available",
            field=models.BooleanField(
                default=False, verbose_name="دفاتر پیشخوان / پست بانک / عابر بانک"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="basij_brother_available",
            field=models.BooleanField(
                default=False, verbose_name="پایگاه بسیج (برادران)"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="basij_sister_available",
            field=models.BooleanField(
                default=False, verbose_name="پایگاه بسیج (خواهران)"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="beautification_plan_available",
            field=models.BooleanField(
                default=False, verbose_name="طرح هادی و زیبا سازی روستا"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="canal_water_available",
            field=models.BooleanField(
                default=False, verbose_name="آب کشاورزی (چاه، قنات و ...)"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="climate",
            field=models.CharField(
                default="", max_length=100, verbose_name="اقلیم آب و هوایی"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="cultural_figures",
            field=models.TextField(default="", verbose_name="شخصیت\u200cهای فرهنگی"),
        ),
        migrations.AddField(
            model_name="village",
            name="development_priorities",
            field=models.TextField(default="", verbose_name="اولویت های اصلی توسعه"),
        ),
        migrations.AddField(
            model_name="village",
            name="doctor_available",
            field=models.BooleanField(default=False, verbose_name="پزشک"),
        ),
        migrations.AddField(
            model_name="village",
            name="drinking_water_available",
            field=models.BooleanField(default=False, verbose_name="آب آشامیدنی"),
        ),
        migrations.AddField(
            model_name="village",
            name="ecotourism_infrastructure_available",
            field=models.BooleanField(
                default=False, verbose_name="بوم گردی و زیرساخت گردشگری"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="electricity_available",
            field=models.BooleanField(default=False, verbose_name="برق"),
        ),
        migrations.AddField(
            model_name="village",
            name="employment_percentage",
            field=models.FloatField(default=0, verbose_name="درصد اشتغال"),
        ),
        migrations.AddField(
            model_name="village",
            name="fuel_station_available",
            field=models.BooleanField(default=False, verbose_name="جایگاه سوخت"),
        ),
        migrations.AddField(
            model_name="village",
            name="gas_available",
            field=models.BooleanField(default=False, verbose_name="گاز"),
        ),
        migrations.AddField(
            model_name="village",
            name="health_center_available",
            field=models.BooleanField(
                default=False,
                verbose_name="مرکز بهداشت / خانه بهداشت / درمانگاه / بیمارستان",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="historical_buildings_available",
            field=models.BooleanField(default=False, verbose_name="ابنیه تاریخی"),
        ),
        migrations.AddField(
            model_name="village",
            name="historical_tourism_background",
            field=models.TextField(default="", verbose_name="پیشینه تاریخی و گردشگری"),
        ),
        migrations.AddField(
            model_name="village",
            name="household_count",
            field=models.IntegerField(default=0, verbose_name="تعداد خانوار"),
        ),
        migrations.AddField(
            model_name="village",
            name="imam_available",
            field=models.BooleanField(default=False, verbose_name="امام جماعت"),
        ),
        migrations.AddField(
            model_name="village",
            name="internet_available",
            field=models.BooleanField(default=False, verbose_name="اینترنت"),
        ),
        migrations.AddField(
            model_name="village",
            name="investment_opportunities",
            field=models.TextField(
                default="", verbose_name="فرصت های اصلی سرمایه گذاری"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="issues_threats",
            field=models.TextField(default="", verbose_name="مشکلات و تهدیدات اصلی"),
        ),
        migrations.AddField(
            model_name="village",
            name="main_needs_solutions",
            field=models.TextField(
                default="", verbose_name="راه\u200cحل فراهم کردن نیاز های اصلی"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="main_occupations",
            field=models.TextField(default="", verbose_name="مشاغل اصلی افراد روستا"),
        ),
        migrations.AddField(
            model_name="village",
            name="migration_percentage",
            field=models.FloatField(default=0, verbose_name="درصد مهاجرت"),
        ),
        migrations.AddField(
            model_name="village",
            name="migration_reason",
            field=models.TextField(default="", verbose_name="علت مهاجرت"),
        ),
        migrations.AddField(
            model_name="village",
            name="mobile_antenna_available",
            field=models.BooleanField(default=False, verbose_name="آنتن موبایل"),
        ),
        migrations.AddField(
            model_name="village",
            name="mosque_available",
            field=models.BooleanField(default=False, verbose_name="مسجد و حسینیه"),
        ),
        migrations.AddField(
            model_name="village",
            name="news_channel_available",
            field=models.BooleanField(
                default=False, verbose_name="کانال خبری و اطلاع رسانی"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="number_of_students",
            field=models.PositiveIntegerField(
                default=0, verbose_name="تعداد دانش\u200cآموزان"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="nurse_available",
            field=models.BooleanField(default=False, verbose_name="بهیار"),
        ),
        migrations.AddField(
            model_name="village",
            name="opportunities_potentials",
            field=models.TextField(
                default="", verbose_name="فرصت ها و پتانسیل های اصلی"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="park_available",
            field=models.BooleanField(default=False, verbose_name="پارک"),
        ),
        migrations.AddField(
            model_name="village",
            name="pathways_available",
            field=models.BooleanField(
                default=False, verbose_name="کانال خبری و اطلاع رسانی"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="people_needs_demands",
            field=models.TextField(
                default="", verbose_name="خواسته و نیازهای اصلی مردم"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="police_available",
            field=models.BooleanField(default=False, verbose_name="پلیس"),
        ),
        migrations.AddField(
            model_name="village",
            name="post_office_available",
            field=models.BooleanField(
                default=False, verbose_name="دفاتر پیشخوان / پست بانک / عابر بانک"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="processed_products_women",
            field=models.TextField(
                default="", verbose_name="محصولات تبدیلی روستا (بانوان)"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="production_workshop_available",
            field=models.BooleanField(
                default=False, verbose_name="کارگاه تولیدی و کشاورزی"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="proximity_to_city",
            field=models.PositiveIntegerField(
                default=0, verbose_name="میزان وابستگی به نزدیکترین شهر"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="raw_products_men",
            field=models.TextField(
                default="", verbose_name="محصولات خام روستا (آقایان)"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="religious_figures",
            field=models.TextField(default="", verbose_name="شخصیت\u200cهای مذهبی"),
        ),
        migrations.AddField(
            model_name="village",
            name="road_available",
            field=models.BooleanField(default=False, verbose_name="جاده و راه ارتباطی"),
        ),
        migrations.AddField(
            model_name="village",
            name="school_available",
            field=models.BooleanField(default=False, verbose_name="مدرسه"),
        ),
        migrations.AddField(
            model_name="village",
            name="scientific_figures",
            field=models.TextField(default="", verbose_name="شخصیت\u200cهای علمی"),
        ),
        migrations.AddField(
            model_name="village",
            name="shop_available",
            field=models.BooleanField(default=False, verbose_name="فروشگاه"),
        ),
        migrations.AddField(
            model_name="village",
            name="sports_figures",
            field=models.TextField(default="", verbose_name="شخصیت\u200cهای ورزشی"),
        ),
        migrations.AddField(
            model_name="village",
            name="sports_hall_available",
            field=models.BooleanField(
                default=False, verbose_name="سالن ورزشی / باشگاه"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="teacher_house_available",
            field=models.BooleanField(default=False, verbose_name="خانه معلم"),
        ),
        migrations.AddField(
            model_name="village",
            name="telephone_available",
            field=models.BooleanField(default=False, verbose_name="تلفن"),
        ),
        migrations.AddField(
            model_name="village",
            name="television_antenna_available",
            field=models.BooleanField(default=False, verbose_name="آنتن تلویزیون"),
        ),
        migrations.AddField(
            model_name="village",
            name="transportation_services_available",
            field=models.BooleanField(default=False, verbose_name="سرویس ایاب ذهاب"),
        ),
        migrations.AddField(
            model_name="village",
            name="village_council_building_available",
            field=models.BooleanField(
                default=False, verbose_name="ساختمان دهیاری و شورا"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="village_head_available",
            field=models.BooleanField(default=False, verbose_name="دهیار"),
        ),
        migrations.AddField(
            model_name="village",
            name="welfare_committee_coverage",
            field=models.PositiveIntegerField(
                default=0, verbose_name="درصد تحت پوشش کمیته و بهزیستی نسبت به جمعیت"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="well_water_available",
            field=models.BooleanField(
                default=False, verbose_name="آب کشاورزی (چاه، قنات و ...)"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="women_income",
            field=models.FloatField(
                default=0, verbose_name="آورده مالی بانوان در روستا"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="women_involvement",
            field=models.BooleanField(
                default=False, verbose_name="از بانوان در مدیریت استفاده شده است؟"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="women_needs_demands",
            field=models.TextField(
                default="", verbose_name="خواسته و نیازهای اصلی بانوان"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="youth_involvement",
            field=models.BooleanField(
                default=False, verbose_name="از جوانان در مدیریت استفاده شده است؟"
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="youth_needs_demands",
            field=models.TextField(
                default="", verbose_name="خواسته و نیازهای اصلی جوانان"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="latitude",
            field=models.FloatField(verbose_name="عرض جغرافیایی"),
        ),
        migrations.AlterField(
            model_name="village",
            name="longitude",
            field=models.FloatField(verbose_name="طول جغرافیایی"),
        ),
        migrations.AlterField(
            model_name="village",
            name="population",
            field=models.IntegerField(default=0, verbose_name="جمعیت"),
        ),
    ]
