# Generated by Django 4.2.4 on 2023-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0004_alter_village_artistic_figures_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="village", name="artistic_figures",),
        migrations.RemoveField(model_name="village", name="canal_water_available",),
        migrations.RemoveField(model_name="village", name="cultural_figures",),
        migrations.RemoveField(model_name="village", name="imam_available",),
        migrations.RemoveField(model_name="village", name="number_of_students",),
        migrations.RemoveField(model_name="village", name="pathways_available",),
        migrations.RemoveField(model_name="village", name="religious_figures",),
        migrations.RemoveField(model_name="village", name="sports_figures",),
        migrations.AddField(
            model_name="village",
            name="brand",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="برند روستا",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="cleric_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="نام و نام خانوادگی روحانی فعلی",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="commitee_members",
            field=models.TextField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="نام و نام خانوادگی اعضای شورای فعلی",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="health_center_chief_doctor",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="پزشک/ رئیس مرکز بهداشت/ کادر درمانی",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="mayor_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="نام و نام خانوادگی دهیار/شهردار فعلی",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="news_channel_names",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="نام کانال های اطلاع رسانی مجازی",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="news_paper",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="نشریه ها و روزنامه های اطلاع رسانی",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="population_pyramid",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="هرم جمعیتی روستا ( وجود نیروی کار بومی)",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="production_workshop",
            field=models.TextField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="عنوان کارگاههای تولیدی کشاورزی و مدیران آنها",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="proposed_entrepreneurship_plan",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="طرح کارآفرینی  پیشنهادی برای روستا",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="resident_council_location_program_time",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="محل هیات مقیم در شاهرود و زمان برنامه های آن",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="school_full_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="نام و نام خانوادگی رئیس و معلمان مدارس",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="village_basij_chief_members",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="رئیس و اعضای پایگاه بسیج روستا",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="bank_available",
            field=models.BooleanField(default=False, verbose_name="بانک"),
        ),
        migrations.AlterField(
            model_name="village",
            name="electricity_available",
            field=models.BooleanField(
                default=False, verbose_name="برق ( تکفاز/ سه فاز)"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="proximity_to_city",
            field=models.PositiveIntegerField(
                default=0, verbose_name=" وابستگی به نزدیکترین شهر"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="scientific_figures",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name="شخصیت\u200cهای علمی,فرهنگی,مذهبی,هنری,ورزشی",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="well_water_available",
            field=models.BooleanField(default=False, verbose_name="آب کشاورزی"),
        ),
    ]
