# Generated by Django 4.2.4 on 2023-10-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0005_remove_village_artistic_figures_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="village", name="proximity_to_city",),
        migrations.AddField(
            model_name="village",
            name="dependency_to_city",
            field=models.TextField(
                blank=True,
                default="",
                null=True,
                verbose_name=" وابستگی به نزدیکترین شهر",
            ),
        ),
    ]
