# Generated by Django 4.2.4 on 2023-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0006_remove_village_proximity_to_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="village", name="cleric_name",),
        migrations.RemoveField(model_name="village", name="climate",),
        migrations.RemoveField(model_name="village", name="commitee_members",),
        migrations.RemoveField(model_name="village", name="dependency_to_city",),
        migrations.RemoveField(
            model_name="village", name="health_center_chief_doctor",
        ),
        migrations.RemoveField(model_name="village", name="household_count",),
        migrations.RemoveField(model_name="village", name="mayor_name",),
        migrations.RemoveField(model_name="village", name="migration_percentage",),
        migrations.RemoveField(model_name="village", name="news_channel_names",),
        migrations.RemoveField(model_name="village", name="news_paper",),
        migrations.RemoveField(model_name="village", name="population_pyramid",),
        migrations.RemoveField(
            model_name="village", name="resident_council_location_program_time",
        ),
        migrations.RemoveField(model_name="village", name="school_full_name",),
        migrations.RemoveField(
            model_name="village", name="village_basij_chief_members",
        ),
        migrations.RemoveField(model_name="village", name="women_income",),
        migrations.RemoveField(model_name="village", name="women_needs_demands",),
        migrations.RemoveField(model_name="village", name="youth_needs_demands",),
        migrations.AddField(
            model_name="village",
            name="unfinished_projects",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="پروژه های نیمه تمام"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="migration_reason",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name=" درصد و علت مهاجرت "
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="production_workshop",
            field=models.TextField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name=" کارگاههای تولیدی کشاورزی و مدیران آنها",
            ),
        ),
    ]
